apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es
  namespace: dev
  labels:
    component: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1                      #Required number of replicas
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      initContainers: #will always initialize before other containers
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:                #specification of normal containers
      - name: es
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: rajivnix/elasticsearch:6.3.2  #specifies the image of elasticsearch to install
        imagePullPolicy: Always
        env:  #List of variables accepted by ES for configuration
        - name: KUBERNETES_CA_CERTIFICATE_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch"
        - name: "NODE_MASTER"
          value: "true"
        - name: "TRANSPORT_PORT"
          value: "9300"
        - name: "HTTP_PORT"
          value: "9200"
        - name: "HTTP_ENABLE"
          value: "true"
        - name: "HTTP_CORS_ENABLE"
          value: "true"
        - name: "HTTP_CORS_ALLOW_ORIGIN"
          value: "*"
        - name: "MEMORY_LOCK"
          value: "false"
        - name: "MINIMUM_MASTER_NODES"
          value: "1"
        
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: gp2
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 10Gi
